M48
; DRILL file {KiCad (7.0.0-0)} date Monday, April 10, 2023 at 07:10:16 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-10T19:10:16-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
%
G90
G05
T1
X2.1063Y-4.0748
X2.1063Y-6.0039
X4.3898Y-4.0748
X4.3913Y-6.0039
T0
M30
