M48
; DRILL file {KiCad (6.0.5-0)} date Monday, July 04, 2022 at 07:17:55 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-07-04T19:17:55-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X53.5Y-103.5
X53.5Y-152.5
X111.5Y-103.5
X111.54Y-152.5
T0
M30
